#!/bin/bash
#
#SBATCH --array=1-7
#SBATCH --error=./jobfiles/dycore_%A-%a.err
#SBATCH --output=./jobfiles/dycore_%A-%a.out
#SBATCH --job-name=dycore_interp
#SBATCH --mem=16G
#SBATCH --time=02:00:00
#SBATCH --verbose
#SBATCH -p serc

FilePath_Base='/oak/stanford/schools/ees/aditis2/dycore/workdir_DELH_4000.0'
FilePath_First=(10 20 30 40 50 60 70 10 20 30 40 50 60 70 10 20 30 40 50 60 70)
FilePath_Second=(0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2)
index=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21)

echo $FilePath_Base/perturb_${FilePath_First[${SLURM_ARRAY_TASK_ID}-1]}_1.${FilePath_Second[${SLURM_ARRAY_TASK_ID}-1]}00000000E-07
cd $FilePath_Base/perturb_${FilePath_First[${SLURM_ARRAY_TASK_ID}-1]}_1.${FilePath_Second[${SLURM_ARRAY_TASK_ID}-1]}00000000E-07

matlab -nodisplay < /home/users/mborrus/Matlab_HPC/scripts/dycore/Aditi_dycore_interp.m
