#!/bin/bash
#
#SBATCH --array=1-2
#SBATCH --error=./jobfiles/regridder_%A-%a.err
#SBATCH --output=./jobfiles/regridder_%A-%a.out
#SBATCH --job-name=regridder_UT
#SBATCH --cpus-per-task=6
#SBATCH --mem=16G
#SBATCH --time=02:00:00
#SBATCH --verbose
#SBATCH -p serc

datapath="/scratch/users/mborrus/AM4/m3"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

datapath="/scratch/users/mborrus/AM4/m2"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

datapath="/scratch/users/mborrus/AM4/m1"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

datapath="/scratch/users/mborrus/AM4/p1"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

datapath="/scratch/users/mborrus/AM4/p2"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

datapath="/scratch/users/mborrus/AM4/p3"
cd $datapath/${SLURM_ARRAY_TASK_ID}

rm -rf FREgrid/
git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock
