#!/bin/bash
#
#SBATCH --array=3-4
#SBATCH --error=./jobfiles/regridder_%A-%a.err
#SBATCH --output=./jobfiles/regridder_%A-%a.out
#SBATCH --job-name=regridder_UT
#SBATCH --cpus-per-task=6
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --verbose
#SBATCH -p serc
conda deactivate

datapath="/scratch/users/mborrus/AM4/SST_m4"
cd $datapath/${SLURM_ARRAY_TASK_ID}

git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock


datapath="/scratch/users/mborrus/AM4/SST_p4"
cd $datapath/${SLURM_ARRAY_TASK_ID}

git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock
