#!/bin/bash
#
#SBATCH --array=1-20
#SBATCH --error=./jobfiles/regridder_%A-%a.err
#SBATCH --output=./jobfiles/regridder_%A-%a.out
#SBATCH --job-name=regridder_UT
#SBATCH --cpus-per-task=6
#SBATCH --mem=8G
#SBATCH --time=00:30:00
#SBATCH --verbose
#SBATCH -p serc
conda deactivate

datapath="/scratch/users/mborrus/AM4/quarter"
cd $datapath/${SLURM_ARRAY_TASK_ID}

mppnccombine -r 19790101.atmos_daily.tile1.nc
mppnccombine -r 19790101.atmos_daily.tile2.nc
mppnccombine -r 19790101.atmos_daily.tile3.nc
mppnccombine -r 19790101.atmos_daily.tile4.nc
mppnccombine -r 19790101.atmos_daily.tile5.nc
mppnccombine -r 19790101.atmos_daily.tile6.nc

git clone https://github.com/mborrus/FREgrid.git
mv -v ./FREgrid/* .
rm -rf FREgrid/
chmod 755 GridRunner_sherlock
./GridRunner_sherlock

